name: Build and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm i

      - name: Unit Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: ./dist

  dev_delpoy:
    name: Dev Deploy
    needs: test_and_build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://catalog-mfe-demo-dev.netlify.app

    steps:
      - name: Download Latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: distribution
          path: dist

      - name: Deploy to Netlify Dev
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "${{ github.event.workflow_run.head_sha }} ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  mfe_e2e:
    name: Micro Frontend E2E
    needs: dev_delpoy
    runs-on: ubuntu-latest

    steps:
      - name: Run Playwright Tests
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm i

      - name: Install Chromium
        run: npx playwright install --with-deps chromium

      - name: Run test
        run: npx playwright test

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Test result
          path: ./html-report
          retention-days: 30

  qa_delpoy:
    name: QA Deploy
    needs: mfe_e2e
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: https://catalog-mfe-staging.netlify.app

    steps:
      - name: Download Latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: distribution
          path: dist

      - name: Deploy to Netlify QA
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "${{ github.event.workflow_run.head_sha }} ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  app_e2e:
    name: App E2E
    needs: qa_delpoy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout E2E Playwright repo
        uses: actions/checkout@v3
        with:
          repository: hoangnguyen-git/e2e-playwright

      - name: Install Dependencies
        run: npm i
  
      - name: Install Chromium
        run: npx playwright install --with-deps chromium

      - name: Run test
        run: npx playwright test

      - name: Generate Allure Report
        if: always()
        run: npm run report

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test result
          path: |
            html-report
            allure-report
          retention-days: 30

  uat_delpoy:
    name: UAT Deploy
    needs: app_e2e
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: https://catalog-mfe.netlify.app

    steps:
      - name: Download Latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: distribution
          path: dist

      - name: Deploy to Netlify Prod
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "${{ github.event.workflow_run.head_sha }} ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
